openapi: 3.0.0
info:
  title: API invits.co
  version: 1.0.0
  description: Merupakan API pembuatan undangan digital

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /api/login:
    $ref: './auth.yaml#/Login'

  /api/register:
    $ref: './auth.yaml#/Register'

  /api/logout:
    $ref: './auth.yaml#/Logout'

  /api/packages:
    $ref: './package.yaml#/Packages'

  /api/packages/{id}:
    $ref: './package.yaml#/Package_id'
  
  /api/themes:
    $ref: './theme.yaml#/Themes'

  /api/themes/{id}:
    $ref: './theme.yaml#/Theme_id'
  
  # /api/orders:
  #   $ref: './order.yaml#/Orders'

  # /api/orders/{id}:
  #   $ref: './order.yaml#/Order_id'
  
  /api/orders/{user_id}:
    $ref: './order.yaml#/Order_user_id'
  
  # /api/weddings:
  #   $ref: './wedding.yaml#/Weddings'

  # /api/weddings/{id}:
  #   $ref: './wedding.yaml#/Wedding_id'
  
  /api/weddings-order/{order_id}:
    $ref: './wedding.yaml#/WeddingOrder_OrderID'
  

