openapi: 3.0.0
info:
  title: API invits.co
  version: 1.0.0
  description: Merupakan API pembuatan undangan digital

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Package:
      $ref: './package.yaml#/components/schemas/Package'
    Theme:
      $ref: './theme.yaml#/components/schemas/Theme'
    Order:
      $ref: './order.yaml#/components/schemas/Order'
    Wedding:
      $ref: './wedding.yaml#/components/schemas/Wedding'
    Wish:
      $ref: './wish.yaml#/components/schemas/Wish'

paths:
  /api/login:
    $ref: './auth.yaml#/Login'

  /api/register:
    $ref: './auth.yaml#/Register'

  /api/logout:
    $ref: './auth.yaml#/Logout'

  /api/packages:
    $ref: './package.yaml#/Packages'

  /api/packages/{id}:
    $ref: './package.yaml#/Package_id'
  
  /api/themes:
    $ref: './theme.yaml#/Themes'

  /api/themes/{id}:
    $ref: './theme.yaml#/Theme_id'
  
  # /api/orders:
  #   $ref: './order.yaml#/Orders'

  /api/orders/{id}:
    $ref: './order.yaml#/Order_id'
  
  /api/orders-user/{user_id}:
    $ref: './order.yaml#/OrderUser_UserID'
  
  # /api/weddings:
  #   $ref: './wedding.yaml#/Weddings'

  # /api/weddings/{id}:
  #   $ref: './wedding.yaml#/Wedding_id'
  
  /api/weddings-order/{order_id}:
    $ref: './wedding.yaml#/WeddingOrder_OrderID'
  
  /api/weddings-invitation/{slug}:
    $ref: './wedding.yaml#/WeddingInvitation_Slug'
  
  /api/wishes:
    $ref: './wish.yaml#/Wishes'

  /api/wishes/{id}:
    $ref: './wish.yaml#/Wish_id'

  /api/wishes-wedding/{wedding_id}:
    $ref: './wish.yaml#/WishesWedding_WeddingID'

  /api/rsvps:
    $ref: './rsvp.yaml#/Rsvps'

  /api/rsvps/{id}:
    $ref: './rsvp.yaml#/Rsvp_id'
  
  /api/rsvps-invitation/{invitation_id}:
    $ref: './rsvp.yaml#/RsvpInvitation_InvitationID'
  

