openapi: 3.0.0
info:
  title: Nama Proyek Anda
  version: 1.0.0
  description: Deskripsi singkat tentang proyek Anda
paths:
  /api/login:
    post:
      tags:
        - Authentication
      summary: Login User
      description: Login user dengan email dan password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: password123
      responses:
        '200':
          description: Login berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    # $ref: '#/components/schemas/User' # Ganti dengan referensi yang sesuai
                  message:
                    type: string
                    example: Login successful.
        '401':
          description: Login gagal
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Login failed.
                  errors:
                    type: object
                    example:
                      login: Invalid email and password combination.
  /api/register:
    post:
      tags:
        - Authentication
      summary: Registrasi User
      description: Registrasi user baru dengan data yang diperlukan.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: John
                last_name:
                  type: string
                  example: Doe
                mobile:
                  type: string
                  example: '1234567890'
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: password123
                c_password:
                  type: string
                  format: password
                  example: password123
      responses:
        '201':
          description: Registrasi berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    # $ref: '#/components/schemas/User' # Ganti dengan referensi yang sesuai
                  message:
                    type: string
                    example: Registration successful.
        '422':
          description: Validasi gagal
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: The given data was invalid.
                  errors:
                    # $ref: '#/components/schemas/ValidationErrors' # Ganti dengan referensi yang sesuai
        '500':
          description: Error server
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Internal server error.
                  errors:
                    type: object
                    example: {}
  /api/logout:
    post:
      tags:
        - Authentication
      summary: Logout User
      description: Logout pengguna saat ini.
      responses:
        '200':
          description: Logout berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Logout successful.
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: John Doe
        email:
          type: string
          format: email
          example: john@example.com
    ValidationErrors:
      type: object
      example: {}
