openapi: 3.0.0
info:
  title: API invits.co
  version: 1.0.0
  description: Merupakan API pembuatan undangan digital

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /api/login:
    $ref: './auth.yaml#/Login'

  /api/register:
    $ref: './auth.yaml#/Register'

  /api/logout:
    $ref: './auth.yaml#/Logout'

  /api/packages:
    $ref: './package.yaml#/Packages'

  /api/packages/{id}:
    $ref: './package.yaml#/Package_id'
